[package]
name = "garygo-jass-pack"
version = "0.1.0"
edition = "2021"
exclude = ["crates/"]

[dependencies]
derive_more = {version = "1.0.0", features = ["from"]}

[workspace]
members = [
  "crates/*"
]
